import React, { useState } from "react";
import { Upload, Cpu, BarChart3, CheckSquare, X } from "lucide-react";

export default function Onboarding({ onClose }) {
  const [currentStep, setCurrentStep] = useState(0);

  const steps = [
    {
      title: "Upload Invoices",
      description: "Drag & drop files or upload multiple invoices in PDF, PNG, JPG, CSV, XML, JSON, or ZIP formats. The ingestion pipeline works instantly.",
      icon: <Upload className="w-12 h-12 text-blue-400" />
    },
    {
      title: "AI Security Verification",
      description: "Our proprietary neural engine performs OCR text extraction, validates vendor registrations, checks payment channels, and identifies duplications.",
      icon: <Cpu className="w-12 h-12 text-emerald-400" />
    },
    {
      title: "Review Fraud Scores",
      description: "Examine detailed risk scores (0-100%) and trust ratings alongside clean explanations and security recommendations generated by explainable AI.",
      icon: <BarChart3 className="w-12 h-12 text-amber-400" />
    },
    {
      title: "Approve or Reject Payments",
      description: "Make informed compliance decisions in one click. Instantly generate downloadable audits and transaction reports for your accounts department.",
      icon: <CheckSquare className="w-12 h-12 text-red-400" />
    }
  ];

  const handleNext = () => {
    if (currentStep < steps.length - 1) {
      setCurrentStep((prev) => prev + 1);
    } else {
      handleComplete();
    }
  };

  const handlePrev = () => {
    if (currentStep > 0) {
      setCurrentStep((prev) => prev - 1);
    }
  };

  const handleComplete = () => {
    localStorage.setItem("fraudshield_onboarding_completed", "true");
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-md flex items-center justify-center z-[999] p-4">
      <div className="glass-panel w-full max-w-lg p-8 relative flex flex-col items-center text-center shadow-[0_0_50px_rgba(59,130,246,0.15)] animate-pulse-glow">
        
        {/* Close Button */}
        <button 
          onClick={handleComplete} 
          className="absolute top-4 right-4 text-gray-400 hover:text-white transition-colors"
          aria-label="Skip onboarding"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Step Indicator */}
        <span className="text-xs font-semibold tracking-widest text-blue-400 uppercase mb-2">
          Step {currentStep + 1} of {steps.length}
        </span>

        {/* Dynamic Icon */}
        <div className="p-4 bg-slate-900/80 rounded-full border border-white/5 mb-6 shadow-inner animate-bounce" style={{ animationDuration: "3s" }}>
          {steps[currentStep].icon}
        </div>

        {/* Step Title */}
        <h2 className="text-2xl font-bold text-white mb-4">
          {steps[currentStep].title}
        </h2>

        {/* Step Description */}
        <p className="text-gray-400 text-sm leading-relaxed mb-8 h-20">
          {steps[currentStep].description}
        </p>

        {/* Pagination Dots */}
        <div className="flex gap-2 mb-8">
          {steps.map((_, idx) => (
            <div 
              key={idx}
              className={`w-2.5 h-2.5 rounded-full transition-all duration-300 ${
                idx === currentStep 
                  ? "bg-blue-400 w-6" 
                  : "bg-white/10"
              }`}
            />
          ))}
        </div>

        {/* Controls */}
        <div className="w-full flex justify-between items-center">
          <button 
            onClick={handleComplete}
            className="text-xs text-gray-400 hover:text-white transition-colors font-medium"
          >
            Skip Walkthrough
          </button>
          
          <div className="flex gap-3">
            {currentStep > 0 && (
              <button 
                onClick={handlePrev}
                className="btn-premium px-4 py-2 text-xs"
              >
                Back
              </button>
            )}
            <button 
              onClick={handleNext}
              className="btn-premium btn-primary px-5 py-2 text-xs"
            >
              {currentStep === steps.length - 1 ? "Get Started" : "Next Step"}
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
